### ISSUE TITLE
Cache path for Homebrew Bundler RubyGems set up by setup-homebrew not valid

### ISSUE THREAD

**Issue by PatTheMav** [Homebrew/actions#319]
The `setup-homebrew` action (`Homebrew/actions/setup-homebrew@master`) has two outputs used to cache installed RubyGems by Homebrew bundler:

* `gems-path`
* `gems-hash`

Without any changes to the workflow files generated by Homebrew for a new tap, this will yield the following paths for macOS and Linux respectively:

* `/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/`
* `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/`

The cache action of both jobs reports an error for both paths however:

* `tar: ../../../../../usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby: Cannot stat: No such file or directory`
* `/usr/bin/tar: ../../../../linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby: Cannot stat: No such file or directory`

The `install-bundler-gems` command was successful in both cases (`Bundled gems are installed into '../../../Homebrew/vendor/bundle'`) and the overall workflow finishes without issues, but the installed gems are never cached.

**Comment by MikeMcQuaid** [comment]
Can you link to an example that's failing? It seems to be working as expected in https://github.com/Homebrew/brew/actions/runs/3573828538/jobs/6008467172#step:3:11

**Comment by Bo98** [comment]
Yeah this is a problem introduced with actions/cache v2 (v1 works and is what we still use in some places).

The problem is v2 strongly assumes `GITHUB_WORKSPACE` and the working directory are identical. While I don't particularly agree with that assumption, we also probably shouldn't be replacing `GITHUB_WORKSPACE` like we do in setup-homebrew.

I'd like to get rid of it and follow the self-hosted path we currently have. There are some compatibility concerns in doing so however, but may have to bite the bullet at some point.

**Comment by PatTheMav** [comment]
So for now the fix is to use the v1 action until you found the bandwidth to update the action? Sounds fair enough, will try to check back every now and then for a new version (or maybe brew spits it out in a changelog).

**Comment by Bo98** [comment]
Yeah we kind of backed ourselves into a corner by recommending `Homebrew/actions/setup-homebrew@master` instead of using a v1 branch.

I think a lot will be ok except a handful of workflows that reference `GITHUB_WORKSPACE` directly. Just need to coordinate that a bit across repos.

**Comment by MikeMcQuaid** [comment]
@Bo98 I guess whatever we do will need to be backwards and forwards compatible 🙃

**Comment by Bo98** [comment]
Somewhat impossible situation given either the symlink exists or it doesn't. The only real middle ground would be to reverse it so that the clone lies in `GITHUB_WORKSPACE` and the symlink is in the `Taps` directory instead.

Still a small compatibility concern for the workflows where we hack a workaround with `rm GITHUB_WORKSPACE`, though we'd want to drop that workaround anyway.

**Comment by Bo98** [comment]
This should now be fixed.
